//
// Created by iacopo on 17/08/20.
//

#ifndef PROGETTO_CONSTANT_H
#define PROGETTO_CONSTANT_H

#endif //PROGETTO_CONSTANT_H

#define AESKEYLENGTH 16
#define AESBLOCKLENGTH 16
#define AESIVLENGTH 16
#define HMACKEYLENGTH 32
#define SHA256DIGESTLENGTH 32
#define MAXMSGLENGTH 8191
#define NONCELENGTH 4
#define MAXUSERNAMELENGTH 17
#define KEYSLENGTH AESKEYLENGTH + AESIVLENGTH + HMACKEYLENGTH
#define ENCRYPTEDKEYLENGTH AESBLOCKLENGTH * 5
#define IVENVELOPELENGTH 16
#define KEYENVELOPELENGTH 256
#define SIGNEDMESSAGELENGTH 256
#define MSGTOSIGNLENGTH ENCRYPTEDKEYLENGTH + IVENVELOPELENGTH + KEYENVELOPELENGTH
#define MAXCERTIFICATELENGTH 4096
#define SIZETLENGTH 2
#define IPLENGTH 4
#define MAXENCRYPTEDUSERLENGTH 32
#define HMACLENGTH 32

////////////////////////////////////////////////////////////////////
//                      MESSAGE LENGTH                          ////
////////////////////////////////////////////////////////////////////

#define CLIENTNONCEMSGLENGTH NONCELENGTH + SHA256DIGESTLENGTH + 1
#define VERIFICATIONNONCEMSGLENGTH NONCELENGTH + SHA256DIGESTLENGTH + 1
#define SERVERNONCEMSGLENGTH 2*NONCELENGTH + SHA256DIGESTLENGTH + 1
#define RESPONSEENCRYPTEDLENGTH 32
#define MAXP2PKEYSMESSAGELENGTH  ENCRYPTEDKEYLENGTH + AESIVLENGTH + KEYENVELOPELENGTH + SIGNEDMESSAGELENGTH
#define CHALLENGERNONCEMESSAGELENGTH 1 + NONCELENGTH*2 + SHA256DIGESTLENGTH
#define CHALLENGEDNONCEMESSAGELENGTH 1 + NONCELENGTH + SHA256DIGESTLENGTH
#define CHALLENGERNONCEVERIFICATIONMESSAGELENGTH 1 + NONCELENGTH + SHA256DIGESTLENGTH
#define CHALLENGEMESSAGELENGTH AESBLOCKLENGTH + SHA256DIGESTLENGTH

#define OPCODELENGTH 1

////////////////////////////////////////////////////////////////////
//                      MESSAGE OPCODE                          ////
////////////////////////////////////////////////////////////////////

#define HELLOMSGCODE 0x00
#define CERTIFICATEMSGCODE 0x01
#define CLIENTREADYCODE 0x02
#define KEYESTABLISHMENTCODE 0x03
#define CLIENTNONCECODE 0x04
#define SERVERNONCECODE 0x05
#define SERVERNONCEVERIFICATIONCODE 0x06
#define PLAYERLISTCODE 0x07
#define PLAYERSELECTEDCODE 0x08
#define SENDCHALLENGECODE 0x08
#define CHALLENGEDRESPONSECODE 0X09
#define OPPONENTKEYCODE 0x0A
#define CLIENTREADY4CHALLENGECODE 0X0B
#define P2PCONNECTIONKEYSCODE 0X0C
#define CHALLENGEDNONCEMESSAGECODE 0X0D
#define CHALLENGERNONCECODE 0X0E
#define CHALLENGERNONCEVERIFICATIONCODE 0X0F
#define CHALLENGEMESSAGECODE 0X10
